#!/usr/bin/env bash

#
# This script will load the user datamart records in ./datamart to
# the SQL server database.
#
# Usage: populate-db <data-query.tar.gz>
#
# This expects a data-query 'tests-with-dependencies' tar.gz file to
# be provided which it will extract then execute.
#
# Configuration will be loaded from environments/$ENVIRONMENT.conf.
# If ENVIRONMENT is not set, `local` is assumed.
#


#
# ENTER SUPPORTED RESOURCE TYPES HERE
#
RESOURCE_TYPES="AllergyIntolerance Condition DiagnosticReport Immunization MedicationStatement"


cd $(dirname $(readlink -f $0))

DQ_TESTS_TAR=${1}
[ -z "$DQ_TESTS_TAR" ] && echo "Usage: $0 <data-query.tar.gz>" && exit 1
[ ! -f "$DQ_TESTS_TAR" ] && echo "Missing $DQ_TESTS_TAR" && exit 1


BASE_DIR=$(pwd)
DATAMART_DIR=$BASE_DIR/datamart
DQ_DIR=$(mktemp -p $BASE_DIR dq-XXXX -d)
CONFIG_FILE=$DQ_DIR/sqlserver.properties

#
# Clean up our mess.
#
onExit() { rm -rf $DQ_DIR; }
trap onExit EXIT


#
# Expand the tests-with-dependencies that includes all of the libraries we'll
# need to run the minimart maker.
#
mkdir -p $DQ_DIR
tar xf $DQ_TESTS_TAR -C $DQ_DIR


#
# Learn what the DB name is from the build.sh script.
#
eval $(grep "export FLYWAY_PLACEHOLDERS_DB_NAME" $BASE_DIR/build.sh)
#
# Learn the other DB variables from the environment config.
#
. $BASE_DIR/environments/${ENVIRONMENT:-local}.conf


#
# Make db configuration properties which is processed by MMM
#
cat <<EOF > $CONFIG_FILE
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=$FLYWAY_BASE_URL;databaseName=$FLYWAY_PLACEHOLDERS_DB_NAME
spring.datasource.username=$FLYWAY_USER
spring.datasource.password=$FLYWAY_PASSWORD
EOF
cat $CONFIG_FILE


#
# Look for a Java 12 that is nearby. If we find one use it (like in the docker image for Jenkins)
# Otherwise, just assume 'java' will magically exist.
#
JAVA_EXE=java
JAVA_12=$(find $EXTRA_JRES -maxdepth 1 -type d -name "jdk-12.*" | head -1)
if [ -n "$JAVA_12" ]
then
  export JAVA_HOME=$JAVA_12
  JAVA_EXE=$JAVA_HOME/bin/java
fi
MAIN_CLASS=gov.va.api.health.dataquery.tools.minimart.MitreMinimartMaker
#
# Execute the MMM for each set of user records, loading each type of supported resource.
#
for USER_RECORDS_DIR in $(find $DATAMART_DIR -maxdepth 1 -type d -name "dm-records-*" | sort)
do
  echo "Loading records in $USER_RECORDS_DIR"
  for RESOURCE_TYPE in $RESOURCE_TYPES
  do
    $JAVA_EXE -cp "$DQ_DIR/*" \
      -Dlogback.configurationFile=$BASE_DIR/logback.xml \
      $MAIN_CLASS $RESOURCE_TYPE $USER_RECORDS_DIR $CONFIG_FILE
  done
done
