#!/usr/bin/env bash

cd $(dirname $(readlink -f $0))

export PATH=$(pwd):$PATH

PROBLEM_CHILDREN=.problem-children

echo "Finding problem children ..."
patients-with-problems > $PROBLEM_CHILDREN

TOTAL=$(cat $PROBLEM_CHILDREN | wc -l)
COUNT=0

for USER in $(cat $PROBLEM_CHILDREN)
do
  let COUNT+=1
  echo "================================================================================"
  echo "USER $USER ($COUNT of $TOTAL)"
  export PATIENT_ID=$USER
  export THREADS=2
  crawl
done

echo "DONE!"
