#!/usr/bin/env bash

cd $(dirname $(readlink -f $0))

export FHIR_DIR=$(readlink -f ../fhir)
USER_LIST=./lab-users.txt
ALL_PROBLEMS=./.problems


listProblems() {
 local p=$1
 PATIENT_DIR=$(dirname $p)
 PROBLEMS=$(find $PATIENT_DIR -regex ".*\(Med[a-z]\|.*P\).*.txt" -exec grep -B 3 "OUTCOME: INVALID" {} \; \
   | grep -E "QUERY.*(patient=|/Medication/).*" \
   | sed 's|.*/dstu2/\([a-zA-Z]\+\).*|\1|' \
   | uniq -c \
   | sed 's/^ *//' \
   | tr ' ' : \
   | paste -sd '  ')
 [ -n "$PROBLEMS" ] && echo "$(cat $PATIENT_DIR/patient-id) $(cat $PATIENT_DIR/icn) ${PROBLEMS}"
}
export -f listProblems

find $FHIR_DIR -name patient-id -type f | sort | xargs -P 8 -I {} bash -c "listProblems {}" | tee $ALL_PROBLEMS



