#!/usr/bin/env bash

cd $(dirname $(readlink -f $0))

export FHIR_DIR=$(readlink -f ../fhir)
USER_LIST=./lab-users.txt
ATTEMPTED=./.attempted

findProblems() {
 local p=$1
 PATIENT_DIR=$(dirname $p)
 FAILURES=$(find $PATIENT_DIR -name "*.txt" -exec grep -l "OUTCOME: INVALID" {} \; | wc -l)
 echo "$FAILURES $(cat $PATIENT_DIR/patient-id) $(cat $PATIENT_DIR/icn)"
}
export -f findProblems

find $FHIR_DIR -name patient-id -type f | sort | xargs -P 8 -I {} bash -c "findProblems {}" > $ATTEMPTED

grep "^[1-9]" $ATTEMPTED | sort -n


